/**
 * S13 WHY / S14 WHAT WE ARE NOT / S15 ORIGIN（蓝图 §3.14）。
 * 全部压缩自 BP 原文段落，事实不改写：DeepSeek 开源的 Harness、1933 年 NYT 影评、
 * 四条「我们不是什么」。
 */

import type { L10n, L10nList } from './types'

export interface Equation {
  before: string[]
  after: string[]
}

export interface ManifestoBlock {
  eyebrow: string
  title: L10n
  paragraphs: L10nList
  pullQuote?: L10n
}

// ── S13 · WHY WE BUILT THIS ─────────────────────────────────
export const why: ManifestoBlock = {
  eyebrow: 'SEC/12',
  title: { en: 'Video is missing its harness layer.', cn: '视频缺的就是 Harness 这一层。' },
  paragraphs: {
    en: [
      'For most creators and brands there is only one way to make video content: take someone else’s creative, work out how to combine it with your own product, and turn it into something of your own. The hard part is reproducing it. As VLMs improved, plenty of products appeared that take an uploaded video and hand back a script breakdown with production notes. For actually reproducing a creative, that step covers maybe one percent of the work.',
      'We worked the same way ourselves when we made content for AI startups: study what other companies ship, borrow the creative. We referenced Perplexity’s Meta ads and borrowed from The Rundown’s UGC ads. Making one of those videos means generating a pile of assets, cutting them, captioning them, timing every effect to the beat. A good editor does two or three a day — even when they are copying a creative outright and only swapping the content.',
      'Video models cannot pull this off on their own. Today’s model is one network painting the whole clip in a single pass, trained on captions as coarse as “a woman cooking in a kitchen.” There is no “caption,” no “B-roll,” no “beat” anywhere in its head, so you cannot give orders to any of them separately. That is set by the generation paradigm, and stacking parameters will not change it: a bigger model paints prettier frames, and the precision still is not there.',
      'For an agent to actually make this content, the work has to happen outside the model. You need a system that turns every atomic step of video production into a component, and a language that all those components are written in, compiled and run by the system, and assembled into the finished film.',
      'DeepSeek’s freshly open-sourced Harness does the same thing. A model on its own gets no work done, so they built a harness around it: tools, sandboxing, scheduling, even the agent’s run loop itself, all organized as swappable plugins. Only then does the model become an agent. They turned everything about the agent into plugins; we turn everything about video-making into components written in SVML, and the system compiles those components into film.',
    ],
    cn: [
      '对大部分创作者和商家来说，做视频内容只有一条路：吸收别人的创意，想办法结合自己的内容和产品，最终转化成自己的东西。难的是复刻。VLM 起来之后，上传视频回一份脚本拆解和制作指导的产品有很多；但对复刻创意来说，这一步几乎没什么用，可能连百分之一的工作都没有搞定。',
      '我们在帮 AI startup 做内容的时候也一样：参考别的公司发的东西，借鉴他们的创意 —— 参考过 Perplexity 的 meta ads，借鉴过 The Rundown 的 UGC 广告。做这样一条视频，要 AIGC 生成许多素材，然后剪辑、配字幕、加特效、完全卡点。很多剪辑一天也就做 2–3 条，哪怕不动脑，照搬创意只改内容。',
      '视频模型自己搞不定这件事。今天的模型是一个网络一口气画出整段画面，训练时见到的描述只有「一个女人在厨房做饭」这种粗粒度文本。它脑子里没有「字幕」「B-roll」「卡点」这些对象，你也就没法单独指挥其中任何一个。这是生成范式决定的，堆参数解决不了：模型再大，画面更好看，但还是没有精确性。',
      '要让 Agent 真正做出这种内容，只能在模型外面下功夫：需要一套系统，把制作视频的每一个元动作变成组件；还需要一门语言，所有组件都用它来写，由系统编译执行，拼成最后的成片。',
      'DeepSeek 刚开源的 Harness 干的就是同一件事。模型本身不干活，他们就在模型外面搭了一层 Harness：工具、沙箱、调度，连 Agent 的运行循环本身，全部做成可替换的插件组织起来，模型这才成了 Agent。他们把 Agent 的一切做成插件，我们把视频制作的一切做成组件写在 SVML 里，再由系统编译成片。',
    ],
  },
  pullQuote: { en: 'Narratage is the Harness for video.', cn: 'Narratage 就是视频的 Harness。' },
}

/** S13 大字等式：第二行逐词替换第一行的词。 */
export const equation: Equation = {
  before: ['Agent', '=', 'Model', '+', 'Harness'],
  after: ['Video Agent', '=', 'Video Model', '+', 'Narratage'],
}

export const equationClosing: L10n = {
  en: 'Narratage is the Harness for video.',
  cn: 'Narratage 就是视频的 Harness。',
}

// ── S14 · WHAT WE ARE NOT ───────────────────────────────────
export interface NegationItem {
  n: number
  title: L10n
  body: L10n
}

export const whatWeAreNotIntro: { eyebrow: string; title: L10n } = {
  eyebrow: 'SEC/14',
  title: { en: 'Four things we are not.', cn: '我们不是的四件事。' },
}

export const whatWeAreNot: NegationItem[] = [
  {
    n: 1,
    title: { en: 'Not a model.', cn: '不是模型。' },
    body: {
      en: 'The system lets you plug in your own image and video models. BYOK: bring your own key.',
      cn: '我们的系统允许用户自行接入图片和视频模型。BYOK，自己带 key。',
    },
  },
  {
    n: 2,
    title: { en: 'Not an editing tool.', cn: '不是剪辑工具。' },
    body: {
      en: 'Not ChatCut, not Palmier. Our users overlap most with people who use HeyGen — people who want the video itself generated by AI: AI talking heads, AI UGC, AI interviews, AI podcasts. If you filmed yourself and want to cut the footage with our framework, that works too. It is just not the group we anchor on.',
      cn: '不是 chatcut，不是 palmier。目标客群的最大公约数就是用 HeyGen 的那群人 —— 想让视频本身由 AI 生成的人：AI 口播、AI UGC、AI 采访、AI 播客。一个人录完视频拿我们的框架来剪，当然没问题，但不是我们最锚定的群体。',
    },
  },
  {
    n: 3,
    title: { en: 'Not a closed product.', cn: '不是封闭的产品。' },
    body: {
      en: 'Compare us with Arcads, TopView, Creatify, MakeUGC, InVideo and Higgsfield — especially Arcads. We are the only open-source one in that group.',
      cn: '可以和 arcads、topview、creatify、makeUGC、invideo、higgsfield 对比，尤其是 arcads。因为我们是其中唯一开源的一个。',
    },
  },
  {
    n: 4,
    title: { en: 'Not a template-driven one-click generator.', cn: '不是模板驱动的「一键生成」。' },
    body: {
      en: 'We ship templates, but you are never locked into them. Modify every component, build your own from scratch, or feed in a video of your own to seed the initial component modules.',
      cn: '我们会放模板，但从来不会把人锁死在模板里：每个组件随时可以改，也可以自己从头搭；你自己输入的视频，也能用来生成最初的那批组件模块。',
    },
  },
]

// ── S15 · ORIGIN ────────────────────────────────────────────
export interface OriginBlock {
  eyebrow: string
  /** ["narration", "montage", "narratage"] —— 前两个词向中间滑动合并。 */
  parts: [string, string, string]
  citation: L10n
  body: L10nList
  closing: L10n
}

export const origin: OriginBlock = {
  eyebrow: 'SEC/15',
  parts: ['narration', 'montage', 'narratage'],
  citation: {
    en: '“The new treatment, which the producer calls ‘narratage,’ is eminently well suited …” — Mordaunt Hall, The New York Times, 1933',
    cn: '“The new treatment, which the producer calls ‘narratage,’ is eminently well suited …” —— Mordaunt Hall，《纽约时报》，1933',
  },
  body: {
    en: [
      'The name comes from a word coined by a New York Times critic reviewing The Power and the Glory in 1933. Producer Jesse L. Lasky’s term described a technique where a narrator’s voice carries the story while the screen assembles scenes to match.',
      'We did not pick it for the history alone. The technique this word describes is this system’s architecture: semantically driven, so what the content says is what the picture assembles. Captions, B-roll and effects all hang on the words of the content — and for AI talking heads, AI avatars, AI UGC and AI podcasts, the skeleton of the video is the spoken content itself. They were born to be compiled this way.',
    ],
    cn: [
      '名字来自 1933 年《纽约时报》影评人为电影 The Power and the Glory 造的词：narration + montage —— 旁白推动故事，画面自动装配蒙太奇。',
      '选这个名字不只是因为典故。Narratage 这个词描述的手法，就是这套系统的架构：语义驱动，内容说什么，画面就装配什么。字幕、B-roll、特效全部挂在内容的词上 —— 而 AI 口播、AI 数字人、AI UGC、AI 播客，这类视频的骨架本来就是说出来的那段内容，天生适合这样编译。',
    ],
  },
  closing: {
    en: 'In 1933 it was a storytelling technique. Today it’s how we compile video.',
    cn: '1933 年它是一种叙事手法，今天它是我们的编译方式。',
  },
}
